shell.run("rm miner")
shell.run("pastebin get MjqSE2RC miner")
shell.run("rm step")
shell.run("pastebin get jseG6ZPL step")
shell.run("rm archie")
shell.run("pastebin get H19M3mwm archie")
shell.run("rm parser")
shell.run("pastebin get a0GF0qyu parser")
shell.run("rm rect")
shell.run("pastebin get MzRUZcw6 rect")
shell.run("rm update")
shell.run("pastebin get 59kKGDDD update")
